### ISSUE TITLE
Wrong path to sourceMap

### ISSUE THREAD

**Issue by kcjpop** [kawan16/mithril-translate#1]
When including directly from `dist` like `<script src="http://127.0.0.1:7777/packages/mithril-translate/dist/mithril-translate.min.js"></script>`, the sourceMap cannot be found.

![screenshot from 2015-04-30 10 33 05](https://cloud.githubusercontent.com/assets/172503/7408319/4dc31ab2-ef24-11e4-862d-290ccbf9f766.png)

**Comment by kawan16** [comment]
Hello, 

I fixed the gruntfile and updated the source map. So, now things should be okay.

That likely comes from a known issue of [grunt-contrib-ugify](https://github.com/gruntjs/grunt-contrib-uglify/issues/71)
