### ISSUE TITLE
RequireJs

### ISSUE THREAD

**Issue by ivancduran** [kawan16/mithril-translate#3]
Please, you can confirm, if the plugin is compatible with require.js

I'm trying to install and give me that errors:

Uncaught SyntaxError: Unexpected token 'e.request.a.onload.a.onerror @ mithril.js:1127d.onreadystatechange @ mithril.js:1067

Thanks for your time.

**Comment by kawan16** [comment]
Hi, not for the moment but I will do it soon. I did it for the router but missed this one.

**Comment by kawan16** [comment]
Well, I made a require-compliant version and pushed on the master branch. Will release with other few changes. I tested on inline translations and "remote" translations with require. Let me know if something wrong.
