### ISSUE TITLE
Mounting component twice

### ISSUE THREAD

**Issue by joakimstrandell** [kawan16/mithril-translate#5]
I can't seem to understand why a component is mounted twice when using mithril translate. Is someone else experiencing the same issue? Is it supposed to be like this?

```
var m = require('mithril');
var mx = require('./mithril-translate');

mx.translate.configure({infix: '/i18n/' , suffix: '.json'});

localize.translate.use('en').then(function() {
    m.route(document.body, "/", {
        "/": {controller: function() {}, view: function() { console.log('Test') }}
    });
});
```

In the example above `Test` is logged twice in the console.

**Comment by kawan16** [comment]
Hi Joakim,

I couldn't reproduce your bug but I got an idea where that can come from. So, I made the fix on the master branch. Let me know if you still get the bug.

**Comment by joakimstrandell** [comment]
Hi @kawan16 

That update worked perfectly. Thanks!

**Comment by jestillore** [comment]
I'm still having this issue.
